version: '3.5'

services:
  redis:
    image: redis:alpine
    container_name: redis-app
    ports:
     - "6379:6379"
    networks:
      - redis
    volumes:
     - ./redisdata:/var/lib/redis/data

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq-app
    ports:
     - "5672:5672"
    networks:
      - rabbitmq
    volumes:
     - ./rabbitmqdata:/var/lib/rabbitmq/data

volumes:
  redisdata:
  rabbitmqdata:
networks:
  redis:
  rabbitmq:
